<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A layout example that shows off a responsive product landing page.">

  <title><?= ! empty($title) ? $title : 'MarioMaker Tracker' ?><?= ! empty($subtitle) ? ' | ' . $subtitle : '' ?></title>

  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="/lib/css/marketing.css">
  <style>
    .pure-menu-link:visited {
      color: #AECFE5;
    }
    .content {
      max-width: 768px;
      margin-left: auto;
      margin-right: auto;
    }
  </style>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.min.js"></script>

</head>

<body>

  <div class="header">
    <div class="home-menu pure-menu pure-menu-horizontal">
      <a class="pure-menu-heading" href="/">MarioMaker Tracker</a>

      <ul class="pure-menu-list">
        <li class="pure-menu-item pure-menu-selected"><a href="/" class="pure-menu-link">Home</a></li>
        <li class="pure-menu-item"><a href="/levels" class="pure-menu-link">Levels</a></li>
      </ul>
    </div>
  </div>


  <div id="layout">

    <div id="main">

      <div class="content">

  <!-- end .header -->