<?php $this->render($response, 'includes/.header.phtml', ['title' => 'MarioMaker Tracker', 'subtitle' => 'Home']); ?>

  <div class="splash-container">
    <div class="splash">
      <h1 class="splash-head">Mario Maker <br>Tracker</h1>
      <p class="splash-subhead">
        Track it like it's hot.
      </p>
      <p>
        <a href="<?= $router->pathFor('levels') ?>" class="pure-button pure-button-primary">Levels</a>
      </p>
    </div>
  </div>

<?php $this->render($response, "includes/.footer.phtml", []); ?>