<?php $this->render($response, 'includes/.header.phtml', ['subtitle' => $level['title']]); ?>

<!-- page-content -->

Level details for <?= $level['title'] ?>

<?php
  // echo '<pre>';
  // print_r($level);
  // die();
 ?>






<?php $this->render($response, "includes/.footer-scripts.phtml", []); ?>

<!-- page-specific javascript -->


<?php $this->render($response, "includes/.footer.phtml", []); ?>