<?php $this->render($response, 'includes/.header.phtml', ['subtitle' => 'Levels']); ?>


    <h1>Levels</h1>

    <form id="searchByCode" class="pure-form" action="javascript:void(0);">
      <label for="search">Search by Level Code</label>
      <div class="pure-g">
        <div class="pure-u-1-3">
          <input type="text" name="search" id="search" value="" placeholder="0000-0000-0000-0000" class="level-code-mask" style="width:auto; text-transform: uppercase;" maxlength="19" >
        </div>
        <div class="pure-u-1-4">
          <input type="submit" value="Search" class="pure-button">
        </div>
      </div>
    </form>
    <form id="searchByUrl" class="pure-form" action="javascript:void(0);">
      <label for="search">Search by Level URL</label>
      <div class="pure-g">
        <div class="pure-u-1-3">
          <input type="text" name="search" id="search" value="" placeholder="https://supermariomakerbookmark.nintendo.net/courses/0000-0000-0000-0000" style="width:auto;">
        </div>
        <div class="pure-u-1-4">
          <input type="submit" value="Search" class="pure-button">
        </div>
      </div>
    </form>

    <!-- <h2>Levels</h2> -->
    <form class="pure-form" action="javascript:void(0);">
    <?php foreach ($levels as $level) { ?>
      <hr>
      <div class="pure-g">
        <div class="pure-u-1-4" style="padding:10px;">
          <a href="<?= $router->pathFor('level', ['level_code' => $level['level_code']]) ?>">
            <img src="<?= $level['image_url'] ?>" class="pure-img" style="margin-top:10px;">
          </a>
        </div>
        <div class="pure-u-3-4" style="padding:10px;">
          <h3><a href="<?= $router->pathFor('level', ['level_code' => $level['level_code']]) ?>"><?= $level['title'] ?></a></h3>
          <input type="text" value="<?= $level['level_code'] ?>" class="pure-input" style="width:auto;" readonly>
          <div class=" pure-menu pure-menu-horizontal">
            <ul class="pure-menu-list">
              <!-- <li><a target="_blank" href="<?=$router->pathFor('scrape-level', ['level_code' => $level['level_code']])?>">Scrape</a></li> -->
              <!-- <li><a target="_blank" href="<?=$router->pathFor('parse-level', ['level_code' => $level['level_code']])?>">Parse</a></li> -->
              <li class="pure-menu-item"><a href="<?= $router->pathFor('level', ['level_code' => $level['level_code']]) ?>" class="pure-menu-link">View</a></li>
            </ul>
          </div>
        </div>
      </div>
    <?php } ?>
      <hr>
    </form>


<?php $this->render($response, "includes/.footer-scripts.phtml", []); ?>

<!-- page-specific javascript -->

<script>
  $(document).ready(function() {

    $('input.level-code-mask').mask('cccc-cccc-cccc-cccc', {
      translation: {
        'c': {
          pattern: /[0-9A-Fa-f]/
        },
        placeholder: "____-____-____-____"
      }
    });

  });

  $(document).on('submit', 'form#searchByCode', function() {
    console.log('submit code form');
    var search = $(this).find('[name=search]').val();
    console.log('search: ' + search);
    if ( search && search.trim().length === 19 ) {
      var levelCode = search.trim().toUpperCase();
      var url = '/levels/' + levelCode;
      window.location = url;
    }
  });
  $(document).on('submit', 'form#searchByUrl', function() {
    console.log('submit url form');
    var search = $(this).find('[name=search]').val();
    if ( search && search.trim().length > 0 ) {
      var tokens = search.split('/');
      if (tokens && tokens.length > 0) {
        var lastSegment = tokens[tokens.length - 1];
        if (lastSegment && lastSegment.trim().length > 0) {
          var levelCode = lastSegment.trim().toUpperCase();
          var url = '/levels/' + levelCode;
          window.location = url;
        }
      }
    }
  });
</script>

<?php $this->render($response, "includes/.footer.phtml", []); ?>