<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>MarioMaker Tracking | Levels</title>

    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>

<body>

    <h1>Levels</h1>

    <!--
      add iteration over existing levels in the system, with links on each to scrape, parse, or view.
      - scrape downloads the current html from its web page
      - parse creates a snapshot of data based on the latest scrape for that level
      - view displays the latest snapshot of data for the level
    -->

    <!-- <h2>Levels</h2> -->
    <?php foreach ($levels as $level) { ?>
      <div class="pure-g">
        <div class="pure-u-1">
          <h3><?= $level['title'] ?>: [<?= $level['level_code'] ?>]</h3>
          <ul>
            <li><a target="_blank" href="<?=$router->pathFor('scrape-level', ['level_code' => $level['level_code']])?>">Scrape</a></li>
            <li><a target="_blank" href="<?=$router->pathFor('parse-level', ['level_code' => $level['level_code']])?>">Parse</a></li>
            <li><a href="<?=/*$router->pathFor('view-level', [])*/''?>">View</a></li>
          </ul>
        </div>
      </div>
    <?php } ?>

</body>
</html>