<?php $this->render($response, 'includes/.header.phtml', ['subtitle' => 'Levels']); ?>

    <h1>Levels</h1>

    <!--
      add iteration over existing levels in the system, with links on each to scrape, parse, or view.
      - scrape downloads the current html from its web page
      - parse creates a snapshot of data based on the latest scrape for that level
      - view displays the latest snapshot of data for the level
    -->

    <!-- <h2>Levels</h2> -->
    <?php foreach ($levels as $level) { ?>
      <div class="pure-g">
        <div class="pure-u-1">
          <h3><?= $level['title'] ?>: [<?= $level['level_code'] ?>]</h3>
          <ul>
            <li><a target="_blank" href="<?=$router->pathFor('scrape-level', ['level_code' => $level['level_code']])?>">Scrape</a></li>
            <li><a target="_blank" href="<?=$router->pathFor('parse-level', ['level_code' => $level['level_code']])?>">Parse</a></li>
            <li><a href="<?=/*$router->pathFor('view-level', [])*/''?>">View</a></li>
          </ul>
        </div>
      </div>
    <?php } ?>


<?php $this->render($response, "includes/.footer.phtml", []); ?>