<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>MarioMaker Tracking</title>

    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>

<body>
    <!--
    Your HTML goes here. Visit purecss.io/layouts/ for some sample HTML code.
    -->

    <h1>Scrape Level</h1>

    <p>
      Scraped Level with level code: <?= $level_code ?>
    </p>

<script>
  // console.log('test');
  // var fifteenMinutesMilliseconds = 15 * 60 * 1000;
  // setTimeout(function(){ location.reload(); }, fifteenMinutesMilliseconds);
</script>
</body>
</html>